#!/usr/bin/env bash
# vim:set ft=bash ts=4 sw=4 et :
# shellcheck shell=bash

set -a

# Install Dnsmasq on macOS
dnsmasq_install() (
  set -a
  orex() { "$@" || exit "$?$(printf >&2 'ERROR[%d]: %s\n' "$?" "$*")"; }

  set +a

  # https://handbook.cal.com/engineering/https-and-subdomains

  orex brew install dnsmasq

  orex cat <<'EOD' >"$(brew --prefix)/etc/dnsmasq.conf"
# Route all *.localhost addresses to localhost
address=/localhost/127.0.0.1

# Don't read /etc/resolv.conf or any other configuration files.
no-resolv

# Never forward plain names (without a dot or domain part)
domain-needed

# Never forward addresses in the non-routed address spaces.
bogus-priv

EOD

  orex brew update

  #orex sudo -i brew services start dnsmasq

  # Make macOS use our local DNS server (Dnsmasq) for .localhost addresses
  # Create the following file at /etc/resolver/localhost:

  orex sudo -i sh -c 'printf %s\n "nameserver 127.0.0.1" > /etc/resolver/localhost'

  printf >&2 '%s\n' "DNS set for *.localhost -> 127.0.0.1"

  printf >&2 '%s\n' "Please run the following command:"
  printf >&2 '%s\n' "sudo brew services start dnsmasq"

)

set +a

case "$([ -f "$0" ] && readlink -f -- "$0")" in
*/dnsmasq-install) { dnsmasq_install "$@"; } ;;
'') {
  printf >&2 '%s\n' "ERROR: [dnsmasq-install] Unable to locate \$0: $0"
  exit 1
} ;;
*) { alias dnsmasq-install="dnsmasq_install"; } ;;
esac
